### ISSUE TITLE
Change behavior %%current_control_set%%

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#120]
`%%current_control_set%%` now maps to `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001` however this should be ControlSet001. The expansion should be used as `HKEY_LOCAL_MACHINE\SYSTEM\%%current_control_set%%` to match the behavior of the OS more closely.

**Comment by joachimmetz** [comment]
@destijl this probably affects GRR as well, so let's make sure to coordinate changes

**Comment by destijl** [comment]
Yep it does. Need to make the change on the GRR side first.

**Comment by destijl** [comment]
This still needs doing, and needs to have a coordinated release with the artifacts repo. But it's a low priority since the current approach works. Releasing so someone else can take it.

**Comment by joachimmetz** [comment]
Per conversation with @grrrrrrrrr we should drop the use of %%current_control_set%% and replace this by HKEY_LOCAL_MACHINE\System\CurrentControlSet. This should work for both grr and plaso (with dfwinreg).
