### ISSUE TITLE
Artifact Sources deprecated fields

### ISSUE THREAD

**Issue by pidydx** [ForensicArtifacts/artifacts#181]
Should supported_os, conditions, and returned_types be getting removed from sources?
Comments in the code indicate they should be removed.
Documentation on style indicates they are correct.

I think ideally ArtifactDefinition.AppendSource() would create a source with all of its valid fields rather than attaching supported_os, conditions, and returned_types in the ArtifactsReader.
Also Source.CopyToDict() should return the entire Source as dict (type, supported_os if defined, conditions if defined, returned_types if defined, attributes) rather than constructing it in ArtifactWriter.

I didn't want to refactor any of this without knowing what direction supported_os, conditions, and returned_types should be going in.

**Comment by joachimmetz** [comment]
* returned_types was removed 
* supported_os needs an overhaul, see https://github.com/ForensicArtifacts/artifacts/issues/274

**Comment by joachimmetz** [comment]
> Comments in the code indicate they should be removed.

Note that this project is not the only implementation e.g. GRR has its own artifacts reader implementation.

**Comment by joachimmetz** [comment]
Removed conditions https://github.com/ForensicArtifacts/artifacts/pull/515
