### ISSUE TITLE
Flaky yapf unit test with newer versions of yapf

### ISSUE THREAD

**Issue by pidydx** [ForensicArtifacts/artifacts#203]
I believe https://github.com/google/yapf/issues/228 changing to exit code 0 has caused https://github.com/ForensicArtifacts/artifacts/blob/master/tests/style_test.py#L17 to not properly detect style violations.

**Comment by destijl** [comment]
Our requirements.txt has yapf pinned at 0.10, which is where we will leave it until diff returns non zero when there's a diff like it should.

https://github.com/google/yapf/issues/325

**Comment by retr0h** [comment]
> Our requirements.txt has yapf pinned at 0.10, which is where we will leave it until diff returns non zero when there's a diff like it should.

Yeah, same here.  Waiting for this to get fixed so we can pin to a newer version.  I have decided to always pin this project.  I've been [bitten before](https://github.com/google/yapf/issues/324).

**Comment by joachimmetz** [comment]
We're on yapf 0.16 now, closing this issue as obsolete
