### ISSUE TITLE
validator add support for COMMAND source type

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#22]

**Comment by destijl** [comment]
So I deliberately excluded COMMAND artifacts when I moved the artifacts over from GRR.  At the time I figured these were GRR specific, but that might have been the wrong call.  You can see we have a bunch here under flow templates:

https://github.com/google/grr/blob/master/artifacts/flow_templates/linux.yaml

GREP is also in a similar situation.

So there's a philosophical question here: does running a command or grepping a file fit with the intent of the artifacts repo to describe where forensically interesting stuff is on the machine?

**Comment by pidydx** [comment]
I think for grepping a file it makes more sense to just say FILE and then a url to how to parse (or build said parser into GRR)

Commands are probably a little different, especially with some of the lesser known command line stuff.  Though you can potentially get into the "which args are the best args" problem.

**Comment by destijl** [comment]
Added COMMAND in https://github.com/ForensicArtifacts/artifacts/pull/28

we should move the COMMAND artifacts over from GRR.  Leaving this open as a reminder to do that.

**Comment by joachimmetz** [comment]
I opt to file a bug/issue with GRR and close it here.

**Comment by joachimmetz** [comment]
@destijl seeing you did most of the work assigning to you. Is this solved by the recent changes?

**Comment by destijl** [comment]
yeah, this is done.
