### ISSUE TITLE
Artifact collector agent

### ISSUE THREAD

**Issue by geekscrapy** [ForensicArtifacts/artifacts#235]
Hi, how are these usually utilised? What tools consume these (apart from GRR).
Are there any stand alone agents?
TIA

**Comment by joachimmetz** [comment]
Artifacts support was recently added to [plaso](https://github.com/log2timeline/plaso) and [Rekall](https://github.com/google/rekall) has its own artifacts support.

**Comment by geekscrapy** [comment]
Thanks, are there any tools in which your can give it a list of these artifacts and it will retrieve them from a running system?

**Comment by joachimmetz** [comment]
GRR
