### ISSUE TITLE
fix failing yapf test

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#248]
https://travis-ci.org/ForensicArtifacts/artifacts/jobs/328929298

likely cause, changes due to new version of yapf

* [x] update yapf in GIFT PPA
* [x] update yapf in l2tbinaries for win32, win64
* [ ] update yapf in l2tbinaries for macos
* [ ] updated source https://codereview.appspot.com/339380043/

**Comment by Onager** [comment]
Looks an issue with the test configuration (no yapf installation):
```
Traceback (most recent call last):
  File "/home/travis/build/ForensicArtifacts/artifacts/tests/style_test.py", line 18, in testCodeStyle
    'yapf', '--diff', '-r', 'artifacts tools', 'artifacts', 'tests'])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by joachimmetz** [comment]
https://github.com/ForensicArtifacts/artifacts/pull/254

**Comment by joachimmetz** [comment]
issue with packaged version of yapf https://codereview.appspot.com/339380043/ and newer version of yapf formatting the source differently.

**Comment by joachimmetz** [comment]
Removed yapf for now, seeing the test was flaky
