### ISSUE TITLE
document artifact definition naming convention

### ISSUE THREAD

**Issue by pidydx** [ForensicArtifacts/artifacts#25]
I have noticed there is a lot of variance between the names and labels for similar things.  What is the best way to align all of these things?

**Comment by joachimmetz** [comment]
I'm working on cleaning up the current format https://github.com/ForensicArtifacts/artifacts/pull/11. Let us know what can be improved and I'll try to see if I can improve the "standard" and the documenation.

**Comment by pidydx** [comment]
It is mostly things like how most of the OSX artifacts start with OSX, but the Linux ones rarely do.  For labels I think just some description around what belongs under each label.  Should OSXLaunchDaemons be System because of the system wide ones, or should it be User because of the user ones, or both, or something else?  That kind of thing.

**Comment by joachimmetz** [comment]
Ack I'll add something to to style guide to make that more consistent and clean that up a bit afterwards.

**Comment by joachimmetz** [comment]
Note to self update documentation to say:

* to keep the name space unique, prefix name of platform specific artifacts with the platform name
* update documentation
* update definitions

**Comment by joachimmetz** [comment]
Dropping labels https://github.com/ForensicArtifacts/artifacts/issues/463

**Comment by joachimmetz** [comment]
First stab at a definition naming convention https://artifacts.readthedocs.io/en/latest/sources/Format-specification.html#name
