### ISSUE TITLE
Remove last returned_types

### ISSUE THREAD

**Issue by cugu** [ForensicArtifacts/artifacts#316]
There is only one returned_types remaining: https://github.com/ForensicArtifacts/artifacts/blob/master/data/windows.yaml#L1224

Can this be removed?

**Comment by joachimmetz** [comment]
Related issue: https://github.com/ForensicArtifacts/artifacts/issues/181

Plaso is not using this. Let me check with the GRR project (@grrrrrrrrr) if they are using this. 

https://github.com/ForensicArtifacts/artifacts/blob/master/docs/Artifacts%20definition%20format%20and%20style%20guide.asciidoc#3-sources

**Comment by joachimmetz** [comment]
https://github.com/google/grr/blob/38fb9f91937896e063ae7cd301dc46bdabced7d0/grr/core/grr_response_core/lib/rdfvalues/artifacts.py#L196

https://github.com/google/grr/blob/d7b8e1b91feac94c9a4a59b36b8a2c84ad9fb700/grr/server/grr_response_server/flows/general/collectors.py#L678

**Comment by joachimmetz** [comment]
Per @demonchild2112 Removing the field from the only artifact that uses it (WindowsPersistenceMechanisms) should not affect collection logic, so feel free to do so.

**Comment by joachimmetz** [comment]
* [x] remove from definitions https://github.com/ForensicArtifacts/artifacts/pull/320
* [ ] have reader / validator report that this keyword is deprecated
* [ ] remove from documentation
