### ISSUE TITLE
Adding FeatureUsage for Windows 10 Taskbar Forensics

### ISSUE THREAD

**Issue by Karneades** [ForensicArtifacts/artifacts#390]
All text copied from https://www.crowdstrike.com/blog/how-to-employ-featureusage-for-windows-10-taskbar-forensics/. My question is, would it be better to have one artifact for the whole key `FeatureUsage\*` or separate artifacts for the subkeys as well.

The FeatureUsage registry key exists within user registry hives (their NTUSER.DAT file), and therefore all information stored within FeatureUsage will be unique for each account.

          NTUSER.DAT\Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage

This key holds the value `KeyCreationTime`.

The FeatureUsage registry key has five subkeys. The keys exist for the purpose of taskbar metrics; however, for a DFIR professional, they can provide valuable insight into the usage of a system by an account.

    AppBadgeUpdated
    AppLaunch
    AppSwitched
    ShowJumpView
    TrayButtonClicked

Each of these keys contains values that correspond to an executable or GUI-based application, the number of times run, and interactions through the taskbar.

**Comment by joachimmetz** [comment]
> My question is, would it be better to have one artifact for the whole key FeatureUsage\* or separate artifacts for the subkeys as well.

I would recommend creating separate definitions for each subkey. Since I assume they each have a different meaning.

You can always create a group to bundle them for ease-of-use
