### ISSUE TITLE
Add Chrome "Web Data" artifact

### ISSUE THREAD

**Issue by obsidianforensics** [ForensicArtifacts/artifacts#424]
Add Chrome "Web Data" artifact (autofill records)

**Comment by joachimmetz** [comment]
@obsidianforensics any more context you can provide? I've assigned this issue to you, assuming you wanted to work on it.

**Comment by joachimmetz** [comment]
There now is ChromiumBasedBrowsersWebDataDatabaseFile, closing issue.
