### ISSUE TITLE
Pulling $Secure:$SDS and $Extend\$UsnJrnl:$J Files

### ISSUE THREAD

**Issue by gremlin205** [ForensicArtifacts/artifacts#431]
Is there a way to do this?

**Comment by joachimmetz** [comment]
@gremlin205 this project does not "pull" anything (assume you mean with pull you mean the ability to collect the content of a data stream in some context). 

If you are asking for definitions to support NTFS ADS then that is already covered by https://github.com/ForensicArtifacts/artifacts/issues/13
