### ISSUE TITLE
Move application definitions into individual definition files

### ISSUE THREAD

**Issue by binglot** [ForensicArtifacts/artifacts#459]
I'd like to suggest 2 changes:
- I think having a label for Hadoop is unnecessary, so I'd remove it.
- I'd move the Hadoop-, Tomcat-, Containerd- and Docker-related definitions from their own files into the Applications yaml file. There's also the Kubernetes file could potentially also go into the Applications yaml file but the file is large enough that I'd keep it separate.

**Comment by sydp** [comment]
Have created a new PR for third party Linux based servers.  We could move Hadoop, Tomcat into this.  WDYT?

https://github.com/ForensicArtifacts/artifacts/pull/521

**Comment by joachimmetz** [comment]
@sydp @binglot what is the status of this? Give #512 was merged is this completed?

**Comment by sydp** [comment]
Discussed with @binglot OOB and this issue has not been completely addressed yet since hadoop/tomcat yaml files are still in the codebase.

**Comment by joachimmetz** [comment]
@sydp I would recommend a proposal/documentation on how to organize such files, so it can be enforced going forwards similar to a style guide (maybe by the validator?).

**Comment by joachimmetz** [comment]
Per chat with @sydp mostly cosmetic changes, will revisit in the future.
