### ISSUE TITLE
Fix Python 3 tests failing on Travis

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#47]
Fix Python 3 tests failing on Travis. Feel free to grab this one otherwise I'll have a look when time permits.

**Comment by destijl** [comment]
I just looked at this.  I couldn't repro locally, they all passed.  I re-ran the test in travis and it passed.  I note travis has been having a bunch of problems and has gone through some change rollbacks.  I don't see anything obviously wrong with the test.
