### ISSUE TITLE
Web access?

### ISSUE THREAD

**Issue by m0untain33r** [ForensicArtifacts/artifacts#502]
I'm new to digital forensics and came across the artifacts database and knowledge repo. Is there a website that hosts this database and knowledge so users can easily add artifact info and knowledge?

**Comment by joachimmetz** [comment]
Per https://github.com/ForensicArtifacts/artifacts-kb/blob/main/README.md https://artifacts-kb.readthedocs.io/en/latest/ or are you looking for something else?

**Comment by joachimmetz** [comment]
Seeing a similar question via email:

The "database" are the YAML files in https://github.com/ForensicArtifacts/artifacts/tree/main/data you don't need to be a developer these are just configuration files.
