### ISSUE TITLE
Add definition for Firefox Cookies

### ISSUE THREAD

**Issue by chb2mn** [ForensicArtifacts/artifacts#561]
- Chrome cookies, check.
- IE cookies, check.

Firefox Cookies missing!

**Comment by joachimmetz** [comment]
@chb2mn is your request to add a definition for Firefox Cookies?

Realize that it is unrealistic to expect the definitions to be all encompassing.

**Comment by chb2mn** [comment]
@joachimmetz Yeah, I'm going to submit a PR for it in a bit. 

good to know though, I didn't know whether it was missing because of some technical reason or just slipped through the crack

**Comment by joachimmetz** [comment]
> good to know though, I didn't know whether it was missing because of some technical reason or just slipped through the crack

the definitions are best effort, basically what people contributed in the past

Happy to separately chat about methodologies to see if coverage can be made measurable and improved

**Comment by joachimmetz** [comment]
> @joachimmetz Yeah, I'm going to submit a PR for it in a bit.

excellent, thanks much appreciated
